### ISSUE TITLE
Change mod location

### ISSUE THREAD

**Issue by scarhcqc** [BaconCatBug/Battleforged-Workshop-Mod-Compilation-Updater#1]
it would be useful if to have a way to change the download location in case they use tabletop sims directory for mods and/or on a different hard drive.

**Comment by BaconCatBug** [comment]
The save game location for Tabletop Simulator does not change. It's always in `Documents/My Games/Tabletop Simulator/Saves` regardless of the setting in TTS. All that setting does is change where your Workshop Mods and downloaded/caches assets are kept.
